---
title: "Further resources"
author: "Maximilian H.K. Hesselbarth"
date: "`r Sys.Date()`"
---

This is a collection of my favorite resources. They are all online and freely available (even though for some book copies can be purchased). If you have a good resource currently not listed, please feel free to [contact me](mailto:mhessel@umich.edu).

## Cheatsheets
Cheatsheets are summaries of certain packages or topics. They can be useful to look up some functionality quickly. Many people even write their own, more specific cheatsheets over time. Here are some cheetsheets relevant for this workshop.

[Base R](cheatsheets/base-r.pdf), [Advanced R](cheatsheets/advanced-r.pdf), [readr](cheatsheets/readr.pdf), [tidyr](cheatsheets/tidyr.pdf), [stringr](cheatsheets/stringr.pdf), [forcats](cheatsheets/forcats.pdf), [dplyr](cheatsheets/dplyr.pdf), [purrr](cheatsheets/purrr.pdf), [ggplot2](cheatsheets/ggplot2.pdf), [sf](cheatsheets/sf.pdf)

## General programming in R
[R for Data Science](https://r4ds.had.co.nz): Book covering many general concepts of data science including different data types, data cleaning, exploration and wrangling.

[Advanced R](https://adv-r.hadley.nz): Book covering more advanced topics of `R` programming such as Environments, Functional and Object-oriented programming, or non-standard evaluation.

[Efficient R programming](https://csgillespie.github.io/efficientR/): Book about how to program more efficiently in `R` including general and specific/advanced advice.

[What They Forgot to Teach You About R](https://rstats.wtf/index.html): Homepage about mainly "daily tasks" in the `R` programming language that are often not covered by courses.

[Big Book of R](https://www.bigbookofr.com/index.html): Massive collection of online-available R books/homepages.

## Data vizualisation using ggplot2

[ggplot2](https://ggplot2-book.org/index.html): Comprehensive book explaining almost all functions of _ggplot2_.

[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/): Book about general data visualization and _ggplot2_.

[A ggplot2 Tutorial for Beautiful Plotting in R](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/): Blog showing how to build many different types of visualizations using _ggplot2_.

[Top 50 ggplot2 visualizations](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html): Homepage with 50 _ggplot2_ visualizations. 
## Spatial data

[Geocomputation with R](https://geocompr.robinlovelace.net/index.html): Book including basics and advanced spatial data background, workflows and examples. Lots of code examples.

[Spatial Data Science](https://keen-swartz-3146c4.netlify.app): Homepage explaining basics of spatial data. Strong focus on `sf` and `stars` package.
