# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branch: [main]

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-renv@v2

      - name: Install spatial dependencies
        run: |
          brew install gdal
          brew install proj

      - name: Install R dependencies
        run: install.packages(c("cowplot", "downloadthis", "palmerpenguins", "rmarkdown", "sf", "terra", "tmap", "tidyverse"))
        shell: Rscript {0}

      - name: Build homepage
        run: rmarkdown::render_site(encoding = "UTF-8")
        shell: Rscript {0}
        
      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit site -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
